[advisories]
ignore = [
    "RUSTSEC-2025-0141", # bincode unmaintained
    "RUSTSEC-2024-0388", # derivative unmaintained
    "RUSTSEC-2024-0384", # instant unmaintained
    "RUSTSEC-2024-0320", # yaml-rust unmaintained
    "RUSTSEC-2024-0436", # paste unmaintained
]
