name: Lock Merged PRs

on:
  pull_request:
    types: [closed]

jobs:
  lock:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Lock PR
        run: gh pr lock ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
