name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-harper-core:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          package-manifest: lib/harper-core/Cargo.toml
          config-file: release-please-config.json

  release-harper-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          package-manifest: lib/harper-ui/Cargo.toml
          config-file: release-please-config.json
          skip-github-release: true
